from rag.embeddings import load_embedding_model
from rag.rag_pipeline import answer_question

# Load embedding model
model = load_embedding_model()

# User question
question = "What was the net interest income in 2025?"

# Run the RAG pipeline
answer, sources = answer_question(
    question=question,
    model=model,
    top_k=5
)

# Display question
print("\n" + "=" * 80)
print("QUESTION")
print("=" * 80)

print(question)

# Display answer
print("\n" + "=" * 80)
print("ANSWER")
print("=" * 80)

print(answer)

# Display sources generated by Python
print("\n" + "=" * 80)
print("RETRIEVED SOURCES")
print("=" * 80)

for i, source in enumerate(sources, start=1):

    print(
        f"{i}. Page {source['page_number']} "
        f"| Chunk ID: {source['chunk_id']} "
        f"| Chunk: {source['chunk_number']}"
    )